version: '1.0.{build}'
#assembly_info:
#  patch: true
#  file: '**\*.csproj'
dotnet_csproj:
  patch: true
  file: 'TestingLab2Framework.csproj'
  version: 4.6
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: TestingLab2Framework.csproj
before_build:
  - nuget restore